### Teacher Login
POST http://localhost:8080/api/auth/login
Content-Type: application/json

{
  "email": "neelam@gmail.com",
  "password": "neelam@123"
}

> {%
    client.global.set("auth-token", response.body.object.token);
    client.global.set("teacherId", response.body.object.userId)
    // console.log(response.body.object)
%}

### Get Student
GET http://localhost:8080/api/teacher/fetch-data
Content-Type: application/json
Authorization: Bearer {{auth-token}}

{
  "teacherId": "{{teacherId}}",
  "subject": "Hindi",
  "period": "ONE",
  "standard": "V",
  "section": "A",
  "date": "2024-03-01"
}

### Mark Attendance
POST http://localhost:8080/api/teacher/save-attendance?standard=V&section=A&date=2024-03-01&subject=Hindi&period=ONE
Content-Type: application/json
Authorization: Bearer {{auth-token}}

[
  {
    "id": null,
    "present": true,
    "name": "Ryan Reynolds",
    "roll": null,
    "standard": "V",
    "section": "A",
    "period": "ONE",
    "subject": "Hindi",
    "teacherId": "25079dd6e7f14bde0c746e714d73bc346d35ac58b68b0d6e5be31e2e4b089985",
    "attendanceType": "SUBJECT",
    "date": "2024-03-01",
    "studentId": "52ae50f109efca57c1fdf311f4f6e013e1615877eaea123858bdc64eaf0bd7d6"
  },
  {
    "id": null,
    "present": true,
    "name": "Robert Downey Jr.",
    "roll": null,
    "standard": "V",
    "section": "A",
    "period": "ONE",
    "subject": "Hindi",
    "teacherId": "4be13cbf82fce4785603cb54a421c9635f214f958aa5d55b08a24950de730fd2",
    "attendanceType": "SUBJECT",
    "date": "2024-03-01",
    "studentId": "3e3a58d18975818248db72a86281f4c8c112e772f94ea23f88c00b3a506f72b8"
  },
  {
    "id": null,
    "present": true,
    "name": "Scarlet Witch",
    "roll": null,
    "standard": "V",
    "section": "A",
    "period": "ONE",
    "subject": "Hindi",
    "teacherId": "972ad8ed238dd9f3cf5943feae20dc973a642471a920cffa1517abc1fddbe3e0",
    "attendanceType": "SUBJECT",
    "date": "2024-03-01",
    "studentId": "0bf8b43b9ca5e43644ee6cad45a51e4a5a64e2b07272af662b229d6251da20a3"
  },
  {
    "id": null,
    "present": true,
    "name": "Thor",
    "roll": null,
    "standard": "V",
    "section": "A",
    "period": "ONE",
    "subject": "Hindi",
    "teacherId": "3313a97cd7717dfe6636947b9434a4cb4eeb0cffffc000bfc2701a0913d09948",
    "attendanceType": "SUBJECT",
    "date": "2024-03-01",
    "studentId": "3458aac02bce961525c8ecc60121e3084581a6f67056b1a3802682780bec669f"
  },
  {
    "id": null,
    "present": true,
    "name": "Star Lord",
    "roll": null,
    "standard": "V",
    "section": "A",
    "period": "ONE",
    "subject": "Hindi",
    "teacherId": "7bc35de92cd43544bf1e88d318d9516ae4956ddf0ac0d9de8ad559f054d7e9fc",
    "attendanceType": "SUBJECT",
    "date": "2024-03-01",
    "studentId": "eef95026a74941523397fbea1502af0721f27265b803d2deeb7c661d3e8abf7e"
  }
]

### Mark Attendance
POST http://localhost:8080/api/teacher/save-attendance?standard=V&section=A&date=2024-03-01&subject=English&period=TWO
Content-Type: application/json
Authorization: Bearer {{auth-token}}

[
  {
    "id": null,
    "present": false,
    "name": "Ryan Reynolds",
    "roll": null,
    "standard": "V",
    "section": "A",
    "period": "TWO",
    "subject": "English",
    "teacherId": "25079dd6e7f14bde0c746e714d73bc346d35ac58b68b0d6e5be31e2e4b089985",
    "attendanceType": "SUBJECT",
    "date": "2024-03-01",
    "studentId": "52ae50f109efca57c1fdf311f4f6e013e1615877eaea123858bdc64eaf0bd7d6"
  },
  {
    "id": null,
    "present": false,
    "name": "Robert Downey Jr.",
    "roll": null,
    "standard": "V",
    "section": "A",
    "period": "TWO",
    "subject": "English",
    "teacherId": "4be13cbf82fce4785603cb54a421c9635f214f958aa5d55b08a24950de730fd2",
    "attendanceType": "SUBJECT",
    "date": "2024-03-01",
    "studentId": "3e3a58d18975818248db72a86281f4c8c112e772f94ea23f88c00b3a506f72b8"
  },
  {
    "id": null,
    "present": false,
    "name": "Scarlet Witch",
    "roll": null,
    "standard": "V",
    "section": "A",
    "period": "TWO",
    "subject": "English",
    "teacherId": "972ad8ed238dd9f3cf5943feae20dc973a642471a920cffa1517abc1fddbe3e0",
    "attendanceType": "SUBJECT",
    "date": "2024-03-01",
    "studentId": "0bf8b43b9ca5e43644ee6cad45a51e4a5a64e2b07272af662b229d6251da20a3"
  },
  {
    "id": null,
    "present": false,
    "name": "Thor",
    "roll": null,
    "standard": "V",
    "section": "A",
    "period": "TWO",
    "subject": "English",
    "teacherId": "3313a97cd7717dfe6636947b9434a4cb4eeb0cffffc000bfc2701a0913d09948",
    "attendanceType": "SUBJECT",
    "date": "2024-03-01",
    "studentId": "3458aac02bce961525c8ecc60121e3084581a6f67056b1a3802682780bec669f"
  },
  {
    "id": null,
    "present": false,
    "name": "Star Lord",
    "roll": null,
    "standard": "V",
    "section": "A",
    "period": "TWO",
    "subject": "English",
    "teacherId": "7bc35de92cd43544bf1e88d318d9516ae4956ddf0ac0d9de8ad559f054d7e9fc",
    "attendanceType": "SUBJECT",
    "date": "2024-03-01",
    "studentId": "eef95026a74941523397fbea1502af0721f27265b803d2deeb7c661d3e8abf7e"
  }
]

### Fetch Marked Attendances
GET http://localhost:8080/api/teacher/fetch-marked
Content-Type: application/json
Authorization: Bearer {{auth-token}}

{
  "teacherId": "{{teacherId}}",
  "subject": "English",
  "period": "TWO",
  "standard": "V",
  "section": "A",
  "date": "2024-03-01"
}

> {%
    // if(response.body.object !== null){
    //     response.body.object.forEach(dto => dto.present = true)
    //     // client.global.set("updated-attendance", response.body.object)
    // }else {}
    // console.log('No object in api response');
 %}

### Update Marked Attendances
PATCH http://localhost:8080//api/teacher/update-marked
Content-Type: application/json
Authorization: Bearer {{auth-token}}

[
  {
    "id": "6d341fd29cd622cd0f23292328399fb17ac25ddcf4c0681996eb52dc4fcf23bd",
    "present": true,
    "name": "Ryan Reynolds",
    "roll": null,
    "standard": "V",
    "section": "A",
    "period": "TWO",
    "subject": "English",
    "teacherId": "96fd3de6db6fbd9f9428b84e90dbc4b0b0e70662c5f403b3f845fadc9b1603a2",
    "attendanceType": "SUBJECT",
    "date": "2024-03-01",
    "studentId": "8b763be6dddfaf9521727d1a7f0d3b2d80387ad548cae62b30ea3ea2cb4da401"
  },
  {
    "id": "55ad4262e419a88bc164c25dcbabd22a4141dd6db51568772f603437578b1bde",
    "present": false,
    "name": "Robert Downey Jr.",
    "roll": null,
    "standard": "V",
    "section": "A",
    "period": "TWO",
    "subject": "English",
    "teacherId": "be60f67150920bbbfb57519c931ed774c3732256096a3baccc31ff90f9183f8a",
    "attendanceType": "SUBJECT",
    "date": "2024-03-01",
    "studentId": "f40f9011cdaa4ec5c861cbf2ef45fe046eb78c9e45557f5d421bbc0349af7d67"
  },
  {
    "id": "4530da519964176c755fb62a71d1137d152a101b201e540cc967cf600bb21561",
    "present": false,
    "name": "Scarlet Witch",
    "roll": null,
    "standard": "V",
    "section": "A",
    "period": "TWO",
    "subject": "English",
    "teacherId": "7181fbec473f6da0e9dc92127663cb376f144cd6e4f0d4c8f6a1b8b1ac308ec4",
    "attendanceType": "SUBJECT",
    "date": "2024-03-01",
    "studentId": "5a075900f7590972e6bce4bf1bc3b39818b33c00e7de2dc95df2927a20664217"
  },
  {
    "id": "dc5e2787ad2e2e56f0530c956b30c53a5bd5a0d895d461432ea6b9a2dd501c75",
    "present": true,
    "name": "Thor",
    "roll": null,
    "standard": "V",
    "section": "A",
    "period": "TWO",
    "subject": "English",
    "teacherId": "db66c92beceb4398c1ba6220f0a66bd8f9549defbd34223551fd51ec8982fffc",
    "attendanceType": "SUBJECT",
    "date": "2024-03-01",
    "studentId": "d78c62924651acabe1bb68e04a237fdf35b998eb4ccb65b04882836357af6d55"
  },
  {
    "id": "216a78e091fe8c236c5bb87d72baf3252e7e93e389df4cd20dd6a7b0eabbd981",
    "present": true,
    "name": "Star Lord",
    "roll": null,
    "standard": "V",
    "section": "A",
    "period": "TWO",
    "subject": "English",
    "teacherId": "148281c1a2ecaaca77b3e9ddc4dfdcbd2e3bba19a079b3ca6db7883315baeeb6",
    "attendanceType": "SUBJECT",
    "date": "2024-03-01",
    "studentId": "ab74ef0a7bca85c79444f4a08c8eb8e64d435e5729782595fa18cbfc62077ded"
  }
]